# Please consult the README.md for some explanations
version: "3.9"

services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cars
    ports:
      - '5432:5432'
    volumes:
      - "postgres:/var/lib/postgresql/data"
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - "pgadmin4:/var/lib/pgadmin"
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:

volumes:
  postgres:
  pgadmin4:
